### ISSUE TITLE
ARM64: Could not find executor for data source type: grafana-influxdb-flux-datasource

### ISSUE THREAD

**Issue by tho-wa** [grafana/influxdb-flux-datasource#104]
2020-05-22T21:53:03+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_addr=46.167.50.235 time_ms=11 size=34 referer="http://grafana.everyonecounts.de/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Flux%20(InfluxDB)%20%5BBETA%5D%22,%7B%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D"
t=2020-05-22T21:53:05+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: grafana-influxdb-flux-datasource" remote_addr=46.167.50.235

Using Grafana 7.0.0 and Flux 7.0.0.

**Comment by tho-wa** [comment]
I have no tried to build it with yarn for my arm64, but still missing gpx_influx_linux_arm64. 

t=2020-05-22T22:50:05+0000 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=grafana-influxdb-flux-datasource error="fork/exec /opt/grafana-influxdb-flux-datasource/dist/gpx_influx_linux_arm64: no such file or directory"

**Comment by ryantxu** [comment]
ahh -- the problem is we do not yet have an arm build!

**Comment by tho-wa** [comment]
Tried to build, but seems to fail, in the nd I have no /dist/gpx_influx_linux_arm64.

ubuntu@ip-172-31-47-213:/opt/grafana-influxdb-flux-datasource$ sudo yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["@grafana/ui@next"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-@grafana-ui-7.0.0-beta.3-5a664b91c1e155205ea67bfb53bffb8f14f7db27-integrity/node_modules/@grafana/ui" as pattern ["@grafana/ui@7.0.0-beta.3","@grafana/ui@7.0.0-beta.3"]. This could result in non-deterministic behavior, skipping.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/api@>= 5.x".
warning "@grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/addons@>= 5.x".
warning "@grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/components@>= 5.x".
warning "@grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/core-events@>= 5.x".
warning "@grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/theming@>= 5.x".
warning "@grafana/runtime > @grafana/ui > @grafana/slate-react > slate-react-placeholder@0.2.9" has unmet peer dependency "slate-react@>=0.22.0".
warning "@grafana/toolkit > @grafana/eslint-config@1.0.0-rc1" has incorrect peer dependency "eslint-plugin-jsdoc@^21.0.0".
warning " > @monaco-editor/react@3.3.0" has unmet peer dependency "prop-types@^15.7.2".
warning " > @monaco-editor/react@3.3.0" has unmet peer dependency "react@^16.8.6".
warning " > @monaco-editor/react@3.3.0" has unmet peer dependency "react-dom@^16.8.6".
[4/4] Building fresh packages...
Done in 329.97s.
ubuntu@ip-172-31-47-213:/opt/grafana-influxdb-flux-datasource$

**Comment by ryantxu** [comment]
flux support was added to grafana 7.1 (released today :tada: )  
https://www.influxdata.com/blog/how-grafana-dashboard-influxdb-flux-influxql/

that has ARM support, so you should be good
