### ISSUE TITLE
7.0. Panic in datasource definition

### ISSUE THREAD

**Issue by andig** [grafana/influxdb-flux-datasource#107]
Happens after upgrading from 5.4.1 to 7.0 using grafana-cli, my dashboards appear empty („no data“) and hitting „Test and Save“ in the Datasource definition gives:

    500 Internal Server Error: {"error":"panic: column retentionPeriod:int is not of type string"}

Looks like a problem with the backend part of the plugin to me. At this stage, neither plugin not dashboards are usable for me anymore. If it helps: I‘m running this agains InfluxDB 1.8.4 with flux enabled.

**Comment by andig** [comment]
Duplicate of #100

**Comment by andig** [comment]
Closing in favour of #101

**Comment by lblabr** [comment]
i tried the above steps, it didn't worked, installing version 5.4.1 in Grafana 7 at least worked, but can't created Data Source in Grafana

`INFO[07-01|07:39:17] Starting Grafana                         logger=server version=7.0.1 commit=ef5b586d7d branch=HEAD compiled=2020-05-26T08:05:56+0000                                                                                                            
INFO[07-01|07:39:17] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini                                                                                                                                              
INFO[07-01|07:39:17] Config loaded from                       logger=settings file=/etc/grafana/grafana.ini                                                                                                                                                          
INFO[07-01|07:39:17] Config overridden from command line      logger=settings arg="default.paths.data=/var/lib/grafana"                                                                                                                                              
INFO[07-01|07:39:17] Config overridden from command line      logger=settings arg="default.paths.logs=/var/log/grafana"                                                                                                                                              
INFO[07-01|07:39:17] Config overridden from command line      logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"                                                                                                                                   
INFO[07-01|07:39:17] Config overridden from command line      logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"                                                                                                                             
INFO[07-01|07:39:17] Config overridden from command line      logger=settings arg="default.log.mode=console"                                                                                                                                                         
INFO[07-01|07:39:17] Config overridden from Environment variable logger=settings var="GF_PATHS_DATA=/var/lib/grafana"                                                                                                                                                
INFO[07-01|07:39:17] Config overridden from Environment variable logger=settings var="GF_PATHS_LOGS=/var/log/grafana"                                                                                                                                                
INFO[07-01|07:39:17] Config overridden from Environment variable logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"                                                                                                                                     
INFO[07-01|07:39:17] Config overridden from Environment variable logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"                                                                                                                               
INFO[07-01|07:39:17] Path Home                                logger=settings path=/usr/share/grafana                                            
....
INFO[07-01|07:39:17] Registering plugin                       logger=plugins name=Finance                                                                                                                                                                            
INFO[07-01|07:39:17] Registering plugin                       logger=plugins name="Flux (InfluxDB) [BETA]"                                                                                                                                                           
INFO[07-01|07:39:18] HTTP Server Listen                       logger=http.server address=[::]:3000 protocol=http subUrl= socket=                                                                                                                                     
INFO[07-01|07:39:21] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.100.10.201 time_ms=0 size=29 referer=                                                                               
EROR[07-01|07:39:41] Plugin not found                         logger=context userId=1 orgId=1 uname=admin error="Plugin not registered"                 `
