### ISSUE TITLE
Self Sign Certificate support for TLS Connection to Influxdb v2

### ISSUE THREAD

**Issue by seanlok** [grafana/influxdb-flux-datasource#111]
Currently the plugin throws error when a new datasource is created with TLS Connection but self sign certificate. The plugin seems to be throwing error `x509: cannot validate  certificate for ...` 

We should implement a skip verify TLS button for this plugin like the v1 plugin.

**Comment by rafecolton** [comment]
Is there any recommended workaround for this?

**Comment by ryantxu** [comment]
flux support was added to grafana 7.1 (released today :tada: )
https://www.influxdata.com/blog/how-grafana-dashboard-influxdb-flux-influxql/

I made a new issue there where we can look at a solution:
https://github.com/grafana/grafana/issues/26388
