### ISSUE TITLE
Transform not working

### ISSUE THREAD

**Issue by wuyb66** [grafana/influxdb-flux-datasource#113]
I want to use **_Transform_** to modify field name. There is no response when click **_Select_** button.
![image](https://user-images.githubusercontent.com/19505239/84125228-d4b55700-aa6e-11ea-8b7c-4413fc5353e7.png)

The **_Transform_** number will change to 1 when select **_Query_** tab.
![image](https://user-images.githubusercontent.com/19505239/84126256-40e48a80-aa70-11ea-9bc6-51743af07231.png)

An unexpected error happened when re-select **_Transform_** tab.
![image](https://user-images.githubusercontent.com/19505239/84126440-79846400-aa70-11ea-80de-015a23ede087.png)

**Comment by M0rdecay** [comment]
It`s [Grafana issue](https://github.com/grafana/grafana/issues/25231). Fixed in 7.0.3.

**Comment by wuyb66** [comment]
It works with Grafana 7.0.3.
