### ISSUE TITLE
Need help setting up flux-datasource

### ISSUE THREAD

**Issue by MoritzLaut** [grafana/influxdb-flux-datasource#115]
my setup:
Grafana: v7.0.3
InfluxDB: 1.8

Hey, 

i want to configure a flux-datasource in grafana but getting an error. I tried to follow this introductions (https://grafana.com/grafana/plugins/grafana-influxdb-flux-datasource) but failed :) 

https://xxx.xxx.com:8086/api/v2/orgs --> HTTP 404 

how can i find my org-id?

What data is required for setting up the flux-datasource?

![image](https://user-images.githubusercontent.com/17141285/84504214-da53ac80-acbb-11ea-9084-3c05ea2ed4a2.png)

best regards
moritz

**Comment by Jordan-prog** [comment]
In order to find the proper URL, you will need to get your org-id. This can be done using a query similar to below:

https://influxdb.company.com:9999/api/v2/orgs

Let us know if you have any luck I was getting the same error in Influx 2.0 beta

**Comment by coussej** [comment]
The above is for influx 2.0. How to find this for 1.8?

**Comment by CharlesGodwin** [comment]
@MoritzLaut Have any luck getting this set up? I'd really like to add a couple of FLUX scripts to my dashboard but have the same 1.8 problem.

**Comment by ryantxu** [comment]
flux support was added to grafana 7.1 (released today :tada: )  There is a pretty good doc helping with the possible combinations here:
https://www.influxdata.com/blog/how-grafana-dashboard-influxdb-flux-influxql/

If you have issues, report them here:
https://github.com/grafana/grafana/issues
