### ISSUE TITLE
Set datasource: connection refused

### ISSUE THREAD

**Issue by wuillg** [grafana/influxdb-flux-datasource#119]
I have installed influxdb 2..0 beta in one docker and the last version of grafana with the plugin flux in an other one. When I am trying to set a datasource with the plugin, I get the following error:

`Get "http://localhost:9999/health": dial tcp 127.0.0.1:9999: connect: connection refused`

![image](https://user-images.githubusercontent.com/67151448/86371007-ab0fda00-bc80-11ea-8a02-9e88011205ee.png)

In the version of the influxdb you have the choice between server and browser and you need to put browser in order to make working.
What I am doing wrong?

**Comment by ryantxu** [comment]
flux support was added to grafana 7.1 (released today :tada: ) 
https://www.influxdata.com/blog/how-grafana-dashboard-influxdb-flux-influxql/

Can you try again in 7.1?  If you hit issues, report them here:
https://github.com/grafana/grafana/issues
