### ISSUE TITLE
Metric request error in 7.1.0

### ISSUE THREAD

**Issue by fhriley** [grafana/influxdb-flux-datasource#122]
I'm still getting some metric request errors in 7.1.0. This query will do it:

```
from(bucket: "dns")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "queries"
    and r["_field"] == "id"
    and r["tap_type"] == "CLIENT_RESPONSE"
    and r["status"] == "NXDOMAIN")
  |> group(columns: ["qname"])
  |> count()
  |> group()
  |> sort(columns: ["_value"], desc: true)
  |> yield(name: "count")
```

This query was copied from influxdb2/chronograf.

**Comment by ryantxu** [comment]
can you post an issue in:
https://github.com/grafana/grafana

please include sample output we can test with:
https://github.com/grafana/grafana/tree/master/pkg/tsdb/influxdb/flux/testdata
