### ISSUE TITLE
Template Variables Don't Replace Properly

### ISSUE THREAD

**Issue by danieldonoghue** [grafana/influxdb-flux-datasource#123]
when using template variables in a flux query, they are replaced with the entire selected set instead of the individual value for that particular panel.

This is contrary to the other data sources where it is replaced with only the value relating to that panel.

I.E., if I set up a variable, `test`, containing `1=abc, 2=hello, 3=there`, use it as the repeat value for my panels and select 2 and 3, according to my InfluxDB query log, `$test` contains `{2,3}`. just selecting a single item in the set works perfectly.

**Comment by ryantxu** [comment]
Can you try using the version in grafana 7.1, and post an issue in the grafana repo with more details (if it is an issue there)?
