### ISSUE TITLE
Plugin cannot be loaded in Grafana v7.3.5

### ISSUE THREAD

**Issue by aniketdey** [grafana/influxdb-flux-datasource#129]
I am trying do AppDynamics integration with Grafana where I have installed a local copy of Grafana and trying to add the AppD data source from the below url which is a forked version of original plugin available in the Grafana website.

https://github.com/oberschlauberger/appdynamics-grafana-datasource

However the data source is throwing error after getting added to grafana.

Please note i have used both dist and src folder under C:\grafana-7.3.5\public\app\plugins\datasource\appdynamics but none works. Please help.

Error in screenshot below
<img width="830" alt="errorgrafana" src="https://user-images.githubusercontent.com/50565861/101795220-b0295d00-3b2d-11eb-8f79-720bc3a3736c.PNG">

**Comment by ryantxu** [comment]
perhaps post an issue on their github repo?
