### ISSUE TITLE
Only _value column gets formatted

### ISSUE THREAD

**Issue by zarbis** [grafana/influxdb-flux-datasource#14]
I'm creating table, containing several fields. This is final part of Flux query (rest is preparing `expense` and `profit` streams):
```
join(tables: {expense: expense, profit: profit}, on: ["_time", "_start", "_stop", "utm_campaign"])
|> map(fn: (r) => {  
  expense: r._value_expense,
  profit: r._value_profit,
  _value: r._value_profit / r._value_expense - 1.0
})
```
When I try to apply formatting to resulting table in Column Styles, all formatting like decimals and thresholds is applied only to `_value` column regardless of whether I put formatting rules in default catch-all `/.*/` rule or into explicitly named column like `profit`. Those non-`_value` columns are also sorted lexicographically despite their type is reported as `double` in query response.

![value](https://user-images.githubusercontent.com/871528/49505101-15398080-f88c-11e8-91c6-6ae1aaecf1f0.png)

I'm not an expert at Grafana code, but looking around [here](https://github.com/grafana/influxdb-flux-datasource/blob/master/src/response_parser.ts#L150) makes me think that `_value` gets hard-coded special treatment.

**Comment by Benzy-Louis** [comment]
I also find this issue annoying.
