### ISSUE TITLE
Flux plugin not working with Influx 1.7

### ISSUE THREAD

**Issue by sslupsky** [grafana/influxdb-flux-datasource#15]
I am using influx 1.7.1 with the flux plugin 5.3.1

I observe a 404 error when trying to connect to the influx database.

Here is the output of the query:

xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/46/v1/query"
params:Object
orgName:"defaultorgname"
q:"from(db: "P286") |> range(start: -1h) |> limit(n:1000) "
data:null
precision:"ms"
response:"404 page not found "

I am running influx 1.7.1 and the flux plugin 5.3.1.

**Comment by sslupsky** [comment]
I should mention that if I connect to my influx database I can run the influx cli with -type=flux and query the database using flux.

**Comment by ryantxu** [comment]
Check #16 -- that seems to make things work in 1.7

**Comment by gowrisankar22** [comment]
I am running into the same issue. When i run below query it returns empty response.
curl localhost:8086/api/v2/query -XPOST -sS -H 'accept:application/csv' -H 'content-type:application/vnd.flux' -d 'from(bucket:"gowridb") |> range(start:-5m) |> filter(fn:(r) => r._measurement == "upload_object")'

I tried with all my measurements except for "mem" measurement rest all returning empty. Are there any workarounds to fix the issue or when this will be fixed ???

**Comment by davkal** [comment]
We've had to change the authentication mechanism to support Influx v2. This might have broken connectivity to 1.7 installs. We're looking into making it work with 1.7 again.

**Comment by adriankuzniewski** [comment]
version 5.2.9 was working fine , 
version 5.3.0 failed 
version 5.3.1 working again.

**Comment by aleveille** [comment]
It's also worth mentioning that even though we're not using Influx 2.0.0, we've had to input values in the `InfluxDB 2.0.0 Details` section

We've used:
Organization: `my-org` (a dummy value used by a previous version of the plugin)
Default Bucket : `mydb` (an actual DB with some measurement so that the plugin can validate the datasource)

**Comment by levkar** [comment]
According to main page, plugin works with 1.7 but 2.0 but, the reality is that it works with 2.0 but 1.7. Shouldn't it support both versions? Would anyone suggest a version that works with 1.7? 
Thanks.

**Comment by voiprodrigo** [comment]
+1 .. Need to authenticate using regular user and password, but those fields are gone, and token is only supported in InfluxDB 2.0.

**Comment by cagriaksay** [comment]
Grafana tests the connection with `from(bucket:"mydatabase/autogen") |> range(start:-10y) |> last()` which timed out in our case. Changing this query live on devtools let us successfully "save & test".

**Comment by superbool** [comment]
Not working in influxdb1.7

**Comment by adriankuzniewski** [comment]
I am working on influx 1.7.6 and Grafana version 6.3.5 Flux plugin 5.3.2 and all working ok except known issue  [#31 ]

**Comment by Saader** [comment]
Hello, 

stop and start docker containers fix the problem for me

**Comment by tatuiot** [comment]
Hi team, same error here trying to connect from my local server and from Grafana free clould account. I created a new influxdb cloud 2.0 account , but still same error. Perhaps something has changed from Influxdb cloud and now unable to connect. 
Network Error: (404) , Telegraf from local server send data normally using same token.

**Comment by jlsam** [comment]
I've been trying to get Flux to connect in Grafana. I had Grafana v6.7.2, InfluxDB 1.7.10 and 
grafana-influxdb-flux-datasource v5.4.1.

I couldn't get it to work, even with 'telegraf/autogen' as Default bucket, as suggested in https://community.influxdata.com/t/influxdb-error-internal-server-error-with-flux-data-source-on-grafana/11210
I was getting the error 

> Data source connected, but has no data. Verify the “bucket” field and make sure the bucket has data.

I tried other logical buckets, but nothing worked.
In the meantime, I could successfully run in CLI
`influx -type=flux -username <user> -password <pass> -execute 'from(bucket:"telegraf")
    |> range(start:-5m)
    |> filter(fn:(r) => r._measurement == "cpu")'`

Then I thought, maybe there is a fix, let me update the packages. And now I'm running InfluxDB 1.8.0 and the same Flux command now returns

> Error: 404 page not found
: 404 Not Found

What would be the simplest command to check connectivity? `buckets()`?
`influx -type=flux -username <user> -password <pass> -execute 'buckets()'`

I think Flux is still enabled in my system after the update. I chose to keep the existing .conf.
`$ cat /etc/influxdb/influxdb.conf | grep flux-enabled
    flux-enabled = true`
