### ISSUE TITLE
release 5.2

### ISSUE THREAD

**Issue by ryantxu** [grafana/influxdb-flux-datasource#18]
In github, it looks like there are lots of releases, however the current release on grafana.com is 5.1.0:
https://grafana.com/plugins/grafana-influxdb-flux-datasource

I see that release-it makes a nice zip, but I don't see how that integrates with the rest of the grafana plugin system.  This plugin is not listed in:
https://github.com/grafana/grafana-plugin-repository/blob/master/repo.json

**Comment by ryantxu** [comment]
FYI, I was able to make this work for [grafana-discrete-panel](https://github.com/NatelEnergy/grafana-discrete-panel) by first making a release branch, then adding this to releaseit:

```
  "scripts": {
    "afterBump": "yarn build; git add --verbose --force dist/;",
    "beforeStage": "cd dist; zip -r natel-discrete-panel-${version}.zip *",
    "afterRelease": "echo Successfully released ${name} v${version} to ${repo.repository}."
  },
```

https://github.com/NatelEnergy/grafana-discrete-panel/blob/master/.release-it.json

**Comment by davkal** [comment]
Releasing is now aligned with how the rest of Grafana plugins are being released. Thanks @briangann
