### ISSUE TITLE
adding datasource getting Network Error: Not Found(404)

### ISSUE THREAD

**Issue by gowrisankar22** [grafana/influxdb-flux-datasource#21]
Hello Colleagues,
I am getting below error while adding the datasource. Could you please help me with this issue ?
influxdb and grafana running on same subnet and i can able to access the influxdb from grafana..

![datasource](https://user-images.githubusercontent.com/20590107/50817164-00e41a00-1349-11e9-9fc2-7cc46c2cb844.PNG)

BRs, Gowrisankar

**Comment by kjedamzik** [comment]
same here 😭

**Comment by kjedamzik** [comment]
presumably related: https://github.com/grafana/influxdb-flux-datasource/issues/15

**Comment by amotl** [comment]
## Solution
Right, you should use the branch [`bucket-updates`](https://github.com/grafana/influxdb-flux-datasource/tree/bucket-updates) by @mattttt as mentioned at https://github.com/grafana/influxdb-flux-datasource/pull/16#issuecomment-448476000.

It already has the essential changes outlined by @ryantxu at https://github.com/grafana/influxdb-flux-datasource/pull/16#issue-239653779.

## Changes
https://github.com/grafana/influxdb-flux-datasource/compare/bucket-updates

## Wash & Go
You can run
```
git clone https://github.com/daq-tools/grafana-influxdb-flux-datasource
```
to clone a repository having this very commit in its default branch (being switched to `develop` there).

**Comment by gowrisankar22** [comment]
@amotl  Still I am running into an below issue.

Plugin Error
Fetch error: 404 Not Found Instantiating https://172.18.110.155/public/plugins/grafana-influxdb-flux-datasource/module.js Loading plugins/grafana-influxdb-flux-datasource/module

When it will be available with a fix to install directly using grafana-cli ??

**Comment by gowrisankar22** [comment]
@amotl cool that did the trick :)
I am running into an another issue. When i run below query it returns empty response.
curl localhost:8086/api/v2/query -XPOST -sS -H 'accept:application/csv' -H 'content-type:application/vnd.flux' -d 'from(bucket:"gowridb") |> range(start:-5m) |> filter(fn:(r) => r._measurement == "upload_object")'

I tried with all my measurements except for "mem" measurement rest all returning empty. Are there any workarounds to fix the issue or when this will be fixed ???

**Comment by amotl** [comment]
Dear @gowrisankar22,

thanks for your answer. Looks like you are almost there, we can confirm that everything turned out well after the yak shaving you are going through right now, see also our [working example](https://swarm.hiveeyes.org/grafana/d/ShvFJL8mk/amo-open-hive-clemens-with-flux). However, we understand getting there can be tricky at first.

### Building the datasource plugin
>> Just run `yarn install` as well as `yarn dev`.
>
> cool that did the trick :)

Good to hear!

### Empty responses from queries
> below query ~~it~~ returns empty response
```
curl localhost:8086/api/v2/query \
  -XPOST -sS -H 'accept:application/csv' -H 'content-type:application/vnd.flux' \
  -d 'from(bucket:"gowridb") |> range(start:-5m) |> filter(fn:(r) => r._measurement == "upload_object")'
```
Sad to hear that. Let me ask you an important question regarding the issue you have.

> except for "mem" measurement rest all returning empty

Are you saying it **actually works** for a **specific** measurement? If so: Congratulations! Then we will have to check what is going wrong with the other measurements.

If not: Bummer, we have to go on  with further digging. Could you add the exact response you are getting from `curl` i.e. how does the _empty response_ actually look like?

Further thoughts: Does your query return anything when omitting the `filter()` part from the expression completely or when expanding the value of the `range()` part to reach out more into the past?

With kind regards,
Andreas.

**Comment by gowrisankar22** [comment]
@amotl Firing an influxquery against the measurement returns the values.
```
curl -G -k -u a:b 'https://influxdb/query?pretty=true' --data-urlencode  "db=graphite" --data-urlencode "q=SELECT * FROM \"upload_object_time7\""

                            "2018-02-12T05:28:05.31858051Z",
                            null,
                            3,
                            "uploadobjecttime7",
                            100
                        ],
                        [
                            "2018-02-12T05:30:07.879465055Z",
                            null,
                            5,
                            "uploadobjecttime7",
                            100
                        ]
```
Same measurement with flux is not working. Please find the outout with verbose mode.

```
root@76027cfcef38:/# curl -v localhost:8086/api/v2/query -XPOST -sS -H 'accept:application/csv' -H 'content-type:application/vnd.flux' -d 'from(bucket:"graphite") |> range(start:-12h) |> filter(fn:(r) => r._measurement == "upload_object")'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8086 (#0)
> POST /api/v2/query HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.52.1
> accept:application/csv
> content-type:application/vnd.flux
> Content-Length: 99
>
* upload completely sent off: 99 out of 99 bytes
< HTTP/1.1 200 OK
< Content-Type: text/csv; charset=utf-8
< Request-Id: 09f85542-185f-11e9-8fad-0242ac130002
< X-Influxdb-Build: OSS
< X-Influxdb-Version: 1.7.2
< X-Request-Id: 09f85542-185f-11e9-8fad-0242ac130002
< Date: Tue, 15 Jan 2019 00:46:47 GMT
< Transfer-Encoding: chunked
<

* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

Flux with measurement mem works fine. Please find the output below.

```
root@76027cfcef38:/# curl -v localhost:8086/api/v2/query -XPOST -sS -H 'accept:application/csv' -H 'content-type:application/vnd.flux' -d 'from(bucket:"graphite") |> range(start:-5m) |> filter(fn:(r) => r._measurement == "mem")'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8086 (#0)
> POST /api/v2/query HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.52.1
> accept:application/csv
> content-type:application/vnd.flux
> Content-Length: 88
>
* upload completely sent off: 88 out of 88 bytes
< HTTP/1.1 200 OK
< Content-Type: text/csv; charset=utf-8
< Request-Id: 4c149c5e-185f-11e9-8fb0-0242ac130002
< X-Influxdb-Build: OSS
< X-Influxdb-Version: 1.7.2
< X-Request-Id: 4c149c5e-185f-11e9-8fb0-0242ac130002
< Date: Tue, 15 Jan 2019 00:48:38 GMT
< Transfer-Encoding: chunked
<
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,mem_used
,,0,2019-01-15T00:43:38.889896002Z,2019-01-15T00:48:38.889896002Z,2019-01-15T00:45:01.589247293Z,45.9623,value,mem,used

* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact

```
After omitting the filter() also it works fine. Please find the response below.

```
root@76027cfcef38:/# curl -v localhost:8086/api/v2/query -XPOST -sS -H 'accept:application/csv' -H 'content-type:application/vnd.flux' -d 'from(bucket:"graphite") |> range(start:-5m)'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8086 (#0)
> POST /api/v2/query HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.52.1
> accept:application/csv
> content-type:application/vnd.flux
> Content-Length: 43
>
* upload completely sent off: 43 out of 43 bytes
< HTTP/1.1 200 OK
< Content-Type: text/csv; charset=utf-8
< Request-Id: a594cfef-1860-11e9-8fb6-0242ac130002
< X-Influxdb-Build: OSS
< X-Influxdb-Version: 1.7.2
< X-Request-Id: a594cfef-1860-11e9-8fb6-0242ac130002
< Date: Tue, 15 Jan 2019 00:58:18 GMT
< Transfer-Encoding: chunked
<
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,mem_used
,,0,2019-01-15T00:53:18.54320513Z,2019-01-15T00:58:18.54320513Z,2019-01-15T00:55:01.943278792Z,46.4183,value,mem,used

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,mem_free
,,1,2019-01-15T00:53:18.54320513Z,2019-01-15T00:58:18.54320513Z,2019-01-15T00:55:01.963915646Z,53.5794,value,memfree,free

* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact`
```
** Just run yarn install as well as yarn dev **This works only when grafana and influxdb is running in the same host (tested works ) but our setup is both are running on a different host as docker container.

**Comment by amotl** [comment]
Hi @gowrisankar22,

thanks for sharing your steps and respective commands with their corresponding outputs.

When looking at them, especially at the last one, it feels like Flux doesn't see the measurement `upload_object_time7` inside the database `graphite` **at all**, at least not within the datetime range `-5m` specified there.

However, this would contradict the output of the very first query you've issued.

Anyway, what is strange is that the measurement names you are using are somehow deviating from each other: While you ask for a measurement `upload_object_time7` in your first example using InfluxQL, the response contains references to `uploadobjecttime7`. On the other hand, in your Flux example where you don't get any results, you are asking for a measurement called `upload_object`.

1. May I humbly ask you to double-check on the "naming things" side with no offense at all?
2. What would extending the datetime range on the last query w/o filtering by measurement name `from(bucket:"graphite") |> range(start:-5m)` actually yield? Maybe this would actually reveal some data from your `upload_object*` measurements?

I'm more or less clueless as well, this is just wannabe educated guessing.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Ah. A small correction here.

> However, this would contradict the output of the very first query you've issued.

Not at all: Depending on which kind of data is in the measurement (table) and at which time you issued the Flux query against it, there could be a reason your observations would actually make sense.

To recap:
- InfluxQL expression
  `SELECT * FROM "upload_object_time7"`
- Flux expression
  `from(bucket:"graphite") |> range(start:-5m)`

Seeing the difference? The InfluxQL statement queries **all the data**, while the Flux one **only for five minutes** into the past.

As one of the timestamps spotted in the output of your first query, `"2018-02-12T05:28:05.31858051Z"`, is already in the past for a few days, it would be obvious it is not selected as a result candidate when asking the database for the most recent five minutes worth of measurement data.

**Comment by gowrisankar22** [comment]
@amotl sorry for the confusion. The actual measurement name is `upload_object_time7`. It was just a copy paste issue. Above in the InfluxQL expression, the result I just copied randomly because the result was too long.
After running below query I see it just returns metrics only for two measurements(mem & memfree) that's why other metrics results are empty(Eventually, we have 1000 of different measurements in influxdb)
from(bucket:"graphite") |> range(start:-5m)

I don't understand why flux is not identifying other measurements. Any idea?

**Comment by amotl** [comment]
Hi @gowrisankar22,

> I got the problem. It was a problem with our test influxdb with measurements. It works fine with our production influxdb.

Glad to hear that!

> [Running] `yarn install` as well as `yarn dev` works only when grafana and influxdb are running on the same host.

This sounds like a different issue. While I'm not an expert on this, I believe it would make sense to start the discussion about that detail in a different issue on GitHub. Then, we would be able to close this one. Agree?

With kind regards,
Andreas.

**Comment by gowrisankar22** [comment]
Yup I agree 👍 @amotl
