### ISSUE TITLE
 Getting Network Error: Not Found(404)

### ISSUE THREAD

**Issue by gowrisankar22** [grafana/influxdb-flux-datasource#22]
Hello Colleagues,
As per the ticket https://github.com/grafana/influxdb-flux-datasource/issues/21 **Just run yarn install as well as yarn dev ** This works only when grafana and influxdb is running in the same host (tested works ) but our setup is both are running on a different host as docker container. Here it is not working. 

Is this due to a bug -- OK and If it is bug When the fix will be available in the GA release?

**Comment by amotl** [comment]
Hi @gowrisankar22,

I think you are referencing https://github.com/grafana/influxdb-flux-datasource/issues/21#issuecomment-453524675 together with the essential question »_When it will be available with a fix to install directly using grafana-cli ??_«, right?

Because, in fact, running `yarn install` as well as `yarn dev` after cloning the repository would be only required when installing from source.

However, @davkal made a fresh release (version 5.2.7) which should include #17 already. So, it should all be good now. Will you give it a try?

Thanks, @davkal!

Cheers,
Andreas.

P.S.: Sorry for not getting into the details regarding your specific Docker setup. However, I don't see any general problems here beside it might be problematic compiling stuff in Docker at all as slim containers usually lack the corresponding infrastructure.

**Comment by gowrisankar22** [comment]
@amotl Thanks a lot of prompt response. I will try as soon as @davkal uploads the bundle to the release.I have tried with source code by doing yarn install and yarn dev bur yarn install gives me some error.
> fsevents@1.2.4: The platform "Linux" is incompatible with this module

But again I am not sure for our setup it works or not or not because our setup is like this.

Host1 --> contains Grafana as a Docker container.
CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS              PORTS                   NAMES
5d31f3d2f147       grafana:latest   "/run.sh"           27 minutes ago      Up 22 minutes       0.0.0.0:443->3000/tcp   grafana

Host2 --> contains influxdb and in front of influx, we setup nginx also as another container.

CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                          NAMES
9e48e15fa2f5        influxdb:1.7.3               "/entrypoint.sh -con…"   46 hours ago        Up 46 hours         8086/tcp                       influxdb
afd9e95222dc        nginx:latest                 "nginx -g 'daemon of…"   7 months ago        Up 12 days          80/tcp, 0.0.0.0:443->443/tcp   nginx

we have exposed an influxdb endpoint on https. (example: https://influxdb.test.com or https://1.1.1.1:443). When someone hits the influxdb endpoint the call goes to nginx on port 443 and it redirects the call to influxdb on http localhost (8086). 

I have tried with 5.2.6 version but it didn't work(404 not found error). Other data sources works perfectly fine except this. 

Please let me know am I missing something.

**Comment by davkal** [comment]
@amotl just did a new release. (Sorry about 5.2.7, the release script was outdated and did not publish the bundled asset.)

**Comment by amotl** [comment]
Dear @gowrisankar22,

again, I don't see a general problem doing this inside Docker. However, it might be problematic compiling stuff in Docker at all as slim containers usually lack the corresponding compiler infrastructure.

`fsevents@1.2.4: The platform "Linux" is incompatible with this module` might be a sign for that.

**Please** open a respective issue like "Problem building plugin from within Docker" to give this an appropriate name if you really want to follow that route. There, we could talk about all things which should be installed inside the Docker container to make building work and maybe even add an appropriate `Dockerfile` to this project. Thanks again!

With kind regards,
Andreas.

**Comment by davkal** [comment]
@gowrisankar22 can you please verify that the containers on different hosts can talk to one another? This needs to be in place because the grafana process in the container on host1 will proxy the queries from the browser to the container on host2. 

You can verify this connection by EXEC'ing into the grafana container and try to curl the nginx container on host2.

**Comment by amotl** [comment]
> just did a new release. (Sorry about 5.2.7, the release script was outdated and did not publish the bundled asset.)

Installing the vanilla 5.2.9 release works like a charm. Thank you very much.

@gowrisankar22: The best I could come up with regarding a streamlined installation from the command line is:
```
# Prepare
apt install wget bsdtar
export PLUGIN_PATH=/var/lib/grafana/plugins/grafana-influxdb-flux-datasource
export PLUGIN_URL=https://github.com/grafana/influxdb-flux-datasource/releases/download/5.2.9/influxdb-flux-datasource-5.2.9.zip

# Install
mkdir -p $PLUGIN_PATH; wget -qO- ${PLUGIN_URL} | bsdtar -xvf- -C ${PLUGIN_PATH}
systemctl restart grafana-server
```

**Comment by gowrisankar22** [comment]
@amotl @davkal Thanks a lot for all the details. I found the root cause of the problem from my side. It was a problem with Nginx configuration where I just allowed few paths. After adding the missing path for flux /api/v2/query to Nginx configuration error was gone but got the popup on grafana to enter the credentials of grafana server. that does not make sense in my opinion, because I'm already logged into grafana as an admin user. After entering grafana credentials on the popup also it is not taking and popup is just kept on coming. Not sure why? another bug ?

Please check the log from grafana:
> t=2019-01-24T14:19:13+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 > uname=xxxx method=POST path=/api/datasources/proxy/173/api/v2/query status=401 > remote_addr=x.x.x.x time_ms=25 size=27 referer=https://xxxxxxxxxx/datasources/edit/173

**Comment by davkal** [comment]
> but got the popup on grafana to enter the credentials of grafana server. that does not make sense in my opinion, because I'm already logged into grafana as an admin user.

Which version of grafana are you using? You may be facing this recent issue: grafana/grafana#15050

**Comment by davkal** [comment]
This seems to work now, as tested in https://github.com/grafana/influxdb-flux-datasource/issues/34#issuecomment-502044405
