### ISSUE TITLE
Build is failing on Linux

### ISSUE THREAD

**Issue by amotl** [grafana/influxdb-flux-datasource#24]
Hi there,

coming from #22, @gowrisankar22 found build problems like
```
fsevents@1.2.4: The platform "Linux" is incompatible with this module
```

While we related this to some Docker quirks on the first hand as building on a vanilla Debian Linux wasn't a problem for us the other day, @davkal [confirmed](https://github.com/grafana/influxdb-flux-datasource/issues/22#issuecomment-457176521) that
> building the plugin on linux is currently failing

Bummer! We will give this a short investigation to find out why this might happen.

Cheers,
Andreas.

**Comment by amotl** [comment]
Hi again,

we can confirm the behavior with current master. However, after finding the appropriate hint with https://github.com/yarnpkg/yarn/issues/2051#issuecomment-450593469 and removing the offending lines in `package.json`:
```diff
diff --git a/package.json b/package.json
index 9296f3b..1734d09 100644
--- a/package.json
+++ b/package.json
@@ -58,9 +58,5 @@
     "typescript": "^2.8.3",
     "webpack": "4.28.4",
     "webpack-cli": "3.2.1"
-  },
-  "resolutions": {
-    "jest/jest-cli/jest-haste-map/sane/fsevents": "1.2.4",
-    "webpack/watchpack/chokidar/fsevents": "1.2.4"
   }
 }
```

`yarn install` and the subsequent `yarn dev` seem to work flawlessly. Maybe you would consider that change as an additional amendment when there are no objections about it.

With kind regards,
Andreas.

**Comment by davkal** [comment]
@briangann are you on Linux?

**Comment by briangann** [comment]
i'm on mac, but those lines are not needed for mac either.  i thought we removed them, must have left out that commit

**Comment by daniellee** [comment]
@amotl this should be fixed in the latest master now

**Comment by briangann** [comment]
please verify this is working now

**Comment by amotl** [comment]
> please verify this is working now

It works like a charm. Thanks!

cc @daniellee and @briangann
