### ISSUE TITLE
Why MAX_SERIES = 20

### ISSUE THREAD

**Issue by nikolay-t** [grafana/influxdb-flux-datasource#31]
Why do we have this in datasource.ts?

MAX_SERIES = 20

**Comment by davkal** [comment]
Wanted to keep the responses performant easy to interpret. We only have 20 colors anyway. But feel free to open a PR to remove it.

**Comment by adriankuzniewski** [comment]
Is there any way we could remove that limitation ?
There is a limitation on populating graphs(also tables) but at the same time it opt-out full csv results. 
Kind regards, 
Adrian.

**Comment by adriankuzniewski** [comment]
changing that MaxSeries to any value is not affecting graphs at all. 
Still getting limit of 20 tables/series. (only on graphs - on csv output - i get all.

**Comment by briangann** [comment]
Let's make this configurable
