### ISSUE TITLE
Unable to create variables 

### ISSUE THREAD

**Issue by ajayanaj** [grafana/influxdb-flux-datasource#32]
Hi,

I'm trying to create variables but it's failing with the attached error.
<img width="1184" alt="Screen Shot 2019-03-27 at 5 22 47 PM" src="https://user-images.githubusercontent.com/45065725/55074008-2addea80-50b5-11e9-8bd8-bc3c109ae7cc.png">

Only tag(telegraf,cpu) showing the result. Any idea why it's throwing the error?

**Comment by ashishkaransingh** [comment]
I am getting the same error.
Response i got:
error
"failed to compile query: type error 3:8-3:34: function does not take a parameter ""by"""
