### ISSUE TITLE
Support for influxDB 2.0 

### ISSUE THREAD

**Issue by suikast42** [grafana/influxdb-flux-datasource#33]
When is planed to support influxdb 2.0 ?

**Comment by botzill** [comment]
Also looking for this. 

Any updates?

Also, would be great to have as well token-based authentication. 

Thx.

**Comment by briangann** [comment]
v2 updates are in progress, expect to have a working plugin by wednesday

**Comment by botzill** [comment]
Thx @briangann!

keep us posted.

**Comment by davkal** [comment]
Done, please upgrade your plugin to v5.3.1
