### ISSUE TITLE
403 Error when adding datasource

### ISSUE THREAD

**Issue by Poc275** [grafana/influxdb-flux-datasource#35]
I get a `Network Error: Forbidden (403)` error when adding Flux as a datasource:

![image](https://user-images.githubusercontent.com/8738684/56959019-f80b9400-6b43-11e9-8e39-184c8bb4c6a0.png)

I'm using Grafana v6.1.6, InfluxDB v1.7.5 and the plugin version is v5.2.11. I've tried with and without Basic Auth but I still get the same error.

I can connect to InfluxDB using the default InfluxDB datasource with the exact same settings.

This is the InfluxDB log when trying to test the connection:
```
[httpd] ::1, ::1,127.0.0.1 - admin [30/Apr/2019:12:35:11 +0100] "POST /api/v2/query HTTP/1.1" 403 100 "-" "Grafana/6.1.6" 03bcb689-6b3c-11e9-8053-0050b68e29b3 0
```
Interestingly, when I test the default InfluxDB data source, the end point is different:
```
[httpd] ::1, ::1,127.0.0.1 - admin [30/Apr/2019:12:38:05 +0100] "GET /query?db=rb3043&epoch=ms&q=SHOW+RETENTION+POLICIES+on+%22rb3043%22 HTTP/1.1" 200 149 "-" "Grafana/6.1.6" 6b72a3ba-6b3c-11e9-8054-0050b68e29b3 2000
```

**Comment by Poc275** [comment]
Apologies for my stupidity. I had enabled flux in the config file but hadn't specified the config file when starting influxd.exe.

**Comment by madhursk** [comment]
> Apologies for my stupidity. I had enabled flux in the config file but hadn't specified the config file when starting influxd.exe.

Hi, how do we specify the config file while starting the influxd.exe, I am facing the same issue network forbidden ( i have made http_enabled= true)
