### ISSUE TITLE
Can not create new line in query editor

### ISSUE THREAD

**Issue by sbenzakountradelab** [grafana/influxdb-flux-datasource#40]
Hi,

I'm using Grafana v6.2.0, influxdb v1.7.4 and influxdb-flux-datasource v[5.3.0] - 2019-06-11.

When i try to create a new line in the text editor, it doesn't work and propose me the list of operator.

Has anyone also met this problem ?

thank you

![image](https://user-images.githubusercontent.com/43436835/59840880-91d90b80-9353-11e9-83ff-beb68179bac8.png)

**Comment by adriankuzniewski** [comment]
Hi there. 
few questions here : 
1) did you enabled flux in influx configuration file https://docs.influxdata.com/flux/v0.24/introduction/installation
2) Have you tested in datasource ? Does it say connected when you save and test ? 
If not - can you try flux from influx cli and test it from there ? - as it might not be grafana issue ? 
3) Can you try to upgrade influx to 1.7.6 as it does support flux 0.24

Cheers :)

**Comment by dswarbrick** [comment]
Pressing enter on its own will send the query to the backend. Press shift-enter to get a newline in the query editor.

**Comment by sbenzakountradelab** [comment]
Tha't it, with shift+enter, it works. Thanks you
