### ISSUE TITLE
Query editor broken

### ISSUE THREAD

**Issue by andig** [grafana/influxdb-flux-datasource#43]
On OSX, both with Safari and Chrome, the query editor behaves erratic:
- return not working (needs shift+return)
- recurring "operators" popup
- keyboard navigation in query textbox (often) not working
- when text contains ^, delete and backspace (often) not working

Noticed all of there on Grafana 6.3.2.

For time being I'd propose to drop the "operators" function and instead rely on a simple but working  textbox.

**Comment by anthonysomerset** [comment]
i am having major issues with the recurring operators popup preventing me from inserting a line break in a query to add some new query in the middle of an existing one - i am having to copy the whole query out into a text editor then re-paste it in

Using most current Chrome on Windows 10 with must current release version of plugin from grafana repo and grafana release

**Comment by ryantxu** [comment]
query editor is now a pretty simple text box... we are looking at integrating the monoco language completion, but that will be in a new issue
