### ISSUE TITLE
Plugin not compatible with Grafana 5.4.x

### ISSUE THREAD

**Issue by dswarbrick** [grafana/influxdb-flux-datasource#47]
Plugin version v5.3.2 shows the following error on Grafana 5.4.1:

![flux-datasource](https://user-images.githubusercontent.com/1667905/66043541-b9796b80-e51f-11e9-9344-5bc3ae58f755.png)

Existing (and previously working) dashboards show a similar error message.

If this is simply due to the plugin toolkit changes in Grafana 5.4, it would be great if you could tag a new release of the plugin, built with the new toolkit.

**Comment by briangann** [comment]
Issue #48

**Comment by briangann** [comment]
unfortunately the changes to the slate editor has made this only work with Grafana 6.4+
