### ISSUE TITLE
Plugin cannot be loaded in Grafana 6.4.1

### ISSUE THREAD

**Issue by aemaem** [grafana/influxdb-flux-datasource#48]
Hi, when adding a new datasource, I get the following error message on the Grafana UI:

Error: Unexpected token '<' Evaluating http://localhost/public/slate-react Loading plugins/grafana-influxdb-flux-datasource/module

Grafana Version 6.4.1

**Comment by briangann** [comment]
the change to slate in Grafana v6.4 has broken compatibility with this plugin.

**Comment by andig** [comment]
Problem confirmed. Influx datasource is broken on Grafana 6.4.

**Comment by lephisto** [comment]
So sad, already using Flux in Production.

**Comment by briangann** [comment]
this will be released 10/11, in the last phase of testing

**Comment by briangann** [comment]
v5.4.0 is out

**Comment by teodoryantcheff** [comment]
Same behavior on 6.4.2.

`Error: Unexpected token '<' Evaluating https://xxxxxx/public/slate-react Loading plugins/grafana-influxdb-flux-datasource/module
`

**Comment by lephisto** [comment]
@teodoryantcheff Did you update Plugins as well? flux datasource works for me @6.4.2 with updates plugins:

```grafana-cli plugins update-all```

**Comment by teodoryantcheff** [comment]
@lephisto `plugins update all` did resolve it. Thanks !

**Comment by aniketdey** [comment]
I am trying to add a AppDynamics data source forked from original plugin. The url is https://github.com/oberschlauberger/appdynamics-grafana-datasource . I am using Grafana v7.3.5 and getting same error while adding the data source. Please suggest way to rectify this.
<img width="830" alt="errorgrafana" src="https://user-images.githubusercontent.com/50565861/101794905-5aed4b80-3b2d-11eb-99e9-57f3bcc89645.PNG">
