### ISSUE TITLE
No possibility to hide/show graph from the same measurement

### ISSUE THREAD

**Issue by m50434** [grafana/influxdb-flux-datasource#66]
Problem:
If I have two querys from the same measurement it is not possible to show/hide one of them (in the GIF the frist panel)

If I have two querys from different measurements there is no problem two hide/show one of them. (in the GIF the second panel)

Here it is in action:
![GIF](https://user-images.githubusercontent.com/24473301/71778188-e029c100-2faa-11ea-9477-22d5ff7ef168.gif)

If Im using "normal" InfluxDB-Query I can also show/hide graphs from the same measurement.

**Comment by ryantxu** [comment]
Is this still true in v7?  if so, can you reopen?  thanks!
