### ISSUE TITLE
 Network Error: Bad Gateway(502)

### ISSUE THREAD

**Issue by Barsonax** [grafana/influxdb-flux-datasource#72]
Iam getting this error I save the datasource:
![image](https://user-images.githubusercontent.com/19387223/76519319-09f6dc80-6461-11ea-8ad0-4f189296c045.png)

Influxdb 1.7.10 (with flux enabled with INFLUXDB_HTTP_FLUX_ENABLED=true)
Grafana 6.6.2

**Comment by Barsonax** [comment]
Ah seems influxdb is now using over 10GB of memory since I enabled flux. Bit much... This is causing it to crash.

**Comment by petramika** [comment]
Hi Barsonax, did that solved your problem? I found myself in the same situations, how did you checked that influxdb is crashing when trying to connect with grafana?

**Comment by petramika** [comment]
> Ah seems influxdb is now using over 10GB of memory since I enabled flux. Bit much... This is causing it to crash.

Hi Barsonax, did that solved your problem? I found myself in the same situations, how did you checked that influxdb is crashing when trying to connect with grafana?

**Comment by Barsonax** [comment]
> Hi Barsonax, did that solved your problem?
I don't see disabling flux as a proper solution.

> I found myself in the same situations, how did you checked that influxdb is crashing when trying to connect with grafana?

I could see the it crashing in kubernetes because it was using too much memory. Memory usage was much lower without flux.

**Comment by petramika** [comment]
> I could see the it crashing in kubernetes because it was using too much memory. Memory usage was much lower without flux.

Well, then at least I dont feel alone :) It looks like it does many petitions and crashes as well through the web browser when doing a query through Grafana. But I am not sure if this is due influxdb v2, flux, grafana or the extension itself. Works but slow.

Did you took any other approach rather than disabling it? I was thinking in just using influxdb v1 and forget about flux.

**Comment by ryantxu** [comment]
not sure what we can do here... lets see if this is an issue with the 7x plugin
