### ISSUE TITLE
add series override does not work

### ISSUE THREAD

**Issue by gwuillou** [grafana/influxdb-flux-datasource#76]
We are using flux, in order to diplay data in grafana. We had tried to use the series override for the visualization but it does not work. 

Is it something already known?

we are using  Grafana 6.5.2 and Influx 1.7.9  and flux v0.50. The grafana-flux plugin is v5.4.1
![override](https://user-images.githubusercontent.com/20662503/77734542-2bcb9400-7009-11ea-9e4e-40e3160967d0.gif)

**Comment by ElieLiabeuf** [comment]
I have the same problem. It works but only with regex. Instead of the "alias" put "/alias/". The bug is still present with the "Fill below to" option as it does not work with regex but only aliases...

**Comment by ryantxu** [comment]
Is this still an issue in 7x?  If it is, can you file an issue in the grafana repo? I do not think it is specific to influx
