### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by gelldur** [grafana/influxdb-flux-datasource#86]
Generally I like idea that data is visible on the right side but...
In some cases or by mistake I get tons of data that will hang my browser... and I will loose my whole progress. Other issue I have is editing query in browser it feels laggy and super slow it would be nice to just have raw text area without any code completion annoying stuff.

![image](https://user-images.githubusercontent.com/175790/80192560-ab07b400-8617-11ea-93d4-162dd1c4036b.png)

On the bottom we see how many result tables and records thats nice info but would be nice to know execution time of query.
___
- [ ] Know the execution time (ok that could be check in "Explore")
- [ ] Disable printing raw data (don't waste memory)
- [ ] Disable advance Flux text field 
- [ ] Disable Query 
![image](https://user-images.githubusercontent.com/175790/80194119-371adb00-861a-11ea-86a4-61fc831de0a7.png) doesn't work :(

Thanks

**Comment by ryantxu** [comment]
@gelldur can you check the 7x version?  this is a pretty dramatic change -- the query is executed and parsed on the server, not in the browser.

re-open this issue if you see anything obvious we should improve.  Thanks
