### ISSUE TITLE
Improve README for 7x

### ISSUE THREAD

**Issue by mertbakir** [grafana/influxdb-flux-datasource#91]
I know this is not an issue but I had to ask. I couldn't configure this plugin using influxdb 1.7.x. It asks for a token and title says "configure influxdb 2.0.0" yet readme says "influxdb 2.0 is not supported."

Can anyone help me if this plugin works with 1.7.x, 1.8.x?

**Comment by Surfict** [comment]
Hello, same problem here. Impossible to connect with credentials as the fields doesn't appear on grafana when you select this option.

**Comment by mertbakir** [comment]
@Surfict Hi, I've tried that too but it returns 504 error.

Is this how you configured?

![image](https://user-images.githubusercontent.com/43188411/81303058-df518a80-9083-11ea-917f-49b2d33d4cfe.png)

Flux already enabled and I can use flux with chronograf on same influxdb instance.

**Comment by joernott** [comment]
I am using grafana 6.7.3 with influxdb 1.8.0 and I am getting 403 errors. It doesn't matter whether I use the limited "grafana" or influx superuser.

Using the same credentials on the CLI "influx" and the regular influxdb plugin works fine.
